version: '3'
services:

  app_python:
    image: dablup/devops_labs:devops_labs
    ports:
      - "5050:5000"
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    mem_limit: 200m

  loki:
    image: grafana/loki:2.6.1
    expose:
      - 3100
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    mem_limit: 200m

  promtail:
    image: grafana/promtail:2.6.1
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    mem_limit: 200m

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ${PWD}/datasources/loki.yml:/etc/grafana/provisioning/datasources/loki_ds.yml
      - ${PWD}/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    expose:
      - 3000
    ports:
      - "3000:3000"
    mem_limit: 200m


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    mem_limit: 200m

volumes:
  prometheus-data: {}
  grafana-data: {}
  loki-data: {}
  promtail-data: {}